// Generated by scripts/generate_collecting_types.py. Do not edit by hand.

export interface Contribution {
  character_id: number;
  request_id: string;
}

export interface Craft {
  recipe: string;
  request_id: string;
}

export interface Equip {
  cosmetic_id?: string | null;
}

export interface EventSpec {
  title: string;
  description: string;
  character_ids: Array<number>;
  goal: number;
  daily_limit?: number;
  reward_label: string;
  starts_at: string;
  ends_at: string;
  request_id: string;
}

export interface Item {
  character_id: number;
  quantity: number;
}

export interface Listing {
  character_id: number;
  quantity: number;
  price: number;
  kind?: "fixed" | "auction";
  hours?: number;
  request_id: string;
}

export interface MarketAction {
  action: "buy" | "bid" | "cancel";
  version: number;
  amount?: number;
  request_id: string;
}

export interface Preferences {
  discoverable?: boolean | null;
  share_inline?: boolean | null;
  preserve_last?: boolean | null;
}

export interface Recycle {
  items: Array<Item>;
  request_id: string;
}

export interface Selection {
  items: Array<Item>;
}

export interface Toggle {
  enabled: boolean;
}

export interface TradeRespond {
  action: "accept" | "reject";
  expected_revision?: number | null;
}

export interface TradeRevision {
  expected_revision: number;
  character_id: number;
}

export interface Wish {
  ids: Array<number>;
  enabled?: boolean;
}
