"""Generate frontend request contracts from the server's Pydantic models, without new tools."""

from __future__ import annotations
import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from source_features import schemas


def ts_type(value):
    if "$ref" in value:
        return value["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in value:
        return " | ".join(ts_type(v) for v in value["anyOf"])
    if "enum" in value:
        return " | ".join(json.dumps(v) for v in value["enum"])
    kind = value.get("type")
    if kind == "array":
        return f"Array<{ts_type(value['items'])}>"
    return {
        "integer": "number",
        "number": "number",
        "string": "string",
        "boolean": "boolean",
        "null": "null",
        "object": "Record<string, unknown>",
    }.get(kind, "unknown")


def build():
    models = {
        name: model
        for name, model in vars(schemas).items()
        if isinstance(model, type)
        and issubclass(model, schemas.Contract)
        and model is not schemas.Contract
    }
    output = [
        "// Generated by scripts/generate_collecting_types.py. Do not edit by hand.\n"
    ]
    for name, model in sorted(models.items()):
        schema = model.model_json_schema()
        output.append(f"export interface {name} {{")
        for key, value in schema["properties"].items():
            suffix = "" if key in schema.get("required", []) else "?"
            output.append(f"  {key}{suffix}: {ts_type(value)};")
        output.append("}\n")
    return "\n".join(output)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "aninexus_frontend/src/features/collecting/contracts.generated.ts"
    result = build()
    if args.check:
        if not target.exists() or target.read_text() != result:
            raise SystemExit("Frontend collecting request contracts are stale")
    else:
        target.write_text(result)
